### ISSUE TITLE
UTF8 not supported?

### ISSUE THREAD

**Issue by dmonizer** [ptarroso/layer2kmz#1]
When trying to export shapefile layer with a label containing "õ", got an error:

Traceback (most recent call last):
File "C:/../plugins\layer2kmz\layer2kmz.py", line 224, in run kmlproc.process()
File "C:/../plugins\layer2kmz\layer2kmz.py", line 347, in process self.processLayer()
File "C:/../plugins\layer2kmz\layer2kmz.py", line 266, in processLayer data.append([str(feature.attributes()[i]) for i in expFieldInd])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf5' in position 6: ordinal not in range(128)

**Comment by ptarroso** [comment]
Thanks for your interest. I will check this.

**Comment by ptarroso** [comment]
The issue is fixed! Now the utf-8 encoding is only handled by kml class. Thanks for reporting.
